name: Create and publish a Docker image to hub.docker.com


on:
  push:
    branches:
      - main
  paths:
      - 'Dockerfile'        # rebuild if Dockerfile changes
      - '**/*.R'            # rebuild if any R files change
      - 'app/**'            # rebuild if files in app folder change
      - 'renv.lock'         # rebuild if R dependencies change

concurrency:
  group: docker-build-main
  cancel-in-progress: true

jobs:
  build:
    if: github.repository == 'AmandaLink/Attitudes_RM-QRPs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set date and time as tag
        id: set_tag
        run: echo "TAG=$(TZ="Europe/Stockholm" date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        
      - name: Build Docker image
        run: docker build -t amandalink/qrp:$TAG -f Dockerfile .
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Publish to Docker Hub
        run: docker push amandalink/qrp:$TAG
