name: Create and publish a Docker image to hub.docker.com

jobs:
  build:
    if: github.repository == 'AmandaLink/Attitudes_RM-QRPs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set date and time as tag
        id: set_tag
        run: echo "TAG=$(TZ="Europe/Stockholm" date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: amandalink/qrp:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
